### ISSUE TITLE
Some examples do not compile with 5.5.1

### ISSUE THREAD

**Issue by Hezkore** [D-a-n-i-l-o/raylib-d_examples#2]
Some examples error out when compiled with Raylib 5.5.1.

From `013_core_3d_camera_first_person`:
```bash
source/app.d(101,17): Error: undefined identifier `CameraYaw`
                CameraYaw(&camera, -135 * DEG2RAD, true);
                ^
source/app.d(102,17): Error: undefined identifier `CameraPitch`
                CameraPitch(&camera, -45 * DEG2RAD, true, true, false);
                ^
```
